// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleMessage.proto

package protobuf.bean;

public final class SampleMessageOuterClass {
  private SampleMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SampleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string sub_message = 9;</code>
     * @return The subMessage.
     */
    java.lang.String getSubMessage();
    /**
     * <code>string sub_message = 9;</code>
     * @return The bytes for subMessage.
     */
    com.google.protobuf.ByteString
        getSubMessageBytes();

    public protobuf.bean.SampleMessageOuterClass.SampleMessage.TestOneofCase getTestOneofCase();
  }
  /**
   * Protobuf type {@code SampleMessage}
   */
  public  static final class SampleMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SampleMessage)
      SampleMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SampleMessage.newBuilder() to construct.
    private SampleMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SampleMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SampleMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SampleMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneofCase_ = 4;
              testOneof_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              testOneofCase_ = 9;
              testOneof_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.bean.SampleMessageOuterClass.internal_static_SampleMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.bean.SampleMessageOuterClass.internal_static_SampleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.bean.SampleMessageOuterClass.SampleMessage.class, protobuf.bean.SampleMessageOuterClass.SampleMessage.Builder.class);
    }

    private int testOneofCase_ = 0;
    private java.lang.Object testOneof_;
    public enum TestOneofCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      NAME(4),
      SUB_MESSAGE(9),
      TESTONEOF_NOT_SET(0);
      private final int value;
      private TestOneofCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TestOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static TestOneofCase forNumber(int value) {
        switch (value) {
          case 4: return NAME;
          case 9: return SUB_MESSAGE;
          case 0: return TESTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TestOneofCase
    getTestOneofCase() {
      return TestOneofCase.forNumber(
          testOneofCase_);
    }

    public static final int NAME_FIELD_NUMBER = 4;
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 4) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneofCase_ == 4) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 4) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 4) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_MESSAGE_FIELD_NUMBER = 9;
    /**
     * <code>string sub_message = 9;</code>
     * @return The subMessage.
     */
    public java.lang.String getSubMessage() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 9) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (testOneofCase_ == 9) {
          testOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string sub_message = 9;</code>
     * @return The bytes for subMessage.
     */
    public com.google.protobuf.ByteString
        getSubMessageBytes() {
      java.lang.Object ref = "";
      if (testOneofCase_ == 9) {
        ref = testOneof_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (testOneofCase_ == 9) {
          testOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (testOneofCase_ == 4) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, testOneof_);
      }
      if (testOneofCase_ == 9) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, testOneof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (testOneofCase_ == 4) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, testOneof_);
      }
      if (testOneofCase_ == 9) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, testOneof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.bean.SampleMessageOuterClass.SampleMessage)) {
        return super.equals(obj);
      }
      protobuf.bean.SampleMessageOuterClass.SampleMessage other = (protobuf.bean.SampleMessageOuterClass.SampleMessage) obj;

      if (!getTestOneofCase().equals(other.getTestOneofCase())) return false;
      switch (testOneofCase_) {
        case 4:
          if (!getName()
              .equals(other.getName())) return false;
          break;
        case 9:
          if (!getSubMessage()
              .equals(other.getSubMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (testOneofCase_) {
        case 4:
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          break;
        case 9:
          hash = (37 * hash) + SUB_MESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getSubMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.bean.SampleMessageOuterClass.SampleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.bean.SampleMessageOuterClass.SampleMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SampleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SampleMessage)
        protobuf.bean.SampleMessageOuterClass.SampleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.bean.SampleMessageOuterClass.internal_static_SampleMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.bean.SampleMessageOuterClass.internal_static_SampleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.bean.SampleMessageOuterClass.SampleMessage.class, protobuf.bean.SampleMessageOuterClass.SampleMessage.Builder.class);
      }

      // Construct using protobuf.bean.SampleMessageOuterClass.SampleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        testOneofCase_ = 0;
        testOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.bean.SampleMessageOuterClass.internal_static_SampleMessage_descriptor;
      }

      @java.lang.Override
      public protobuf.bean.SampleMessageOuterClass.SampleMessage getDefaultInstanceForType() {
        return protobuf.bean.SampleMessageOuterClass.SampleMessage.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.bean.SampleMessageOuterClass.SampleMessage build() {
        protobuf.bean.SampleMessageOuterClass.SampleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.bean.SampleMessageOuterClass.SampleMessage buildPartial() {
        protobuf.bean.SampleMessageOuterClass.SampleMessage result = new protobuf.bean.SampleMessageOuterClass.SampleMessage(this);
        if (testOneofCase_ == 4) {
          result.testOneof_ = testOneof_;
        }
        if (testOneofCase_ == 9) {
          result.testOneof_ = testOneof_;
        }
        result.testOneofCase_ = testOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.bean.SampleMessageOuterClass.SampleMessage) {
          return mergeFrom((protobuf.bean.SampleMessageOuterClass.SampleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.bean.SampleMessageOuterClass.SampleMessage other) {
        if (other == protobuf.bean.SampleMessageOuterClass.SampleMessage.getDefaultInstance()) return this;
        switch (other.getTestOneofCase()) {
          case NAME: {
            testOneofCase_ = 4;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case SUB_MESSAGE: {
            testOneofCase_ = 9;
            testOneof_ = other.testOneof_;
            onChanged();
            break;
          }
          case TESTONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.bean.SampleMessageOuterClass.SampleMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.bean.SampleMessageOuterClass.SampleMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int testOneofCase_ = 0;
      private java.lang.Object testOneof_;
      public TestOneofCase
          getTestOneofCase() {
        return TestOneofCase.forNumber(
            testOneofCase_);
      }

      public Builder clearTestOneof() {
        testOneofCase_ = 0;
        testOneof_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 4) {
          ref = testOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneofCase_ == 4) {
            testOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 4) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneofCase_ == 4) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 4;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        if (testOneofCase_ == 4) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testOneofCase_ = 4;
        testOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string sub_message = 9;</code>
       * @return The subMessage.
       */
      public java.lang.String getSubMessage() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 9) {
          ref = testOneof_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (testOneofCase_ == 9) {
            testOneof_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sub_message = 9;</code>
       * @return The bytes for subMessage.
       */
      public com.google.protobuf.ByteString
          getSubMessageBytes() {
        java.lang.Object ref = "";
        if (testOneofCase_ == 9) {
          ref = testOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (testOneofCase_ == 9) {
            testOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sub_message = 9;</code>
       * @param value The subMessage to set.
       * @return This builder for chaining.
       */
      public Builder setSubMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  testOneofCase_ = 9;
        testOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sub_message = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubMessage() {
        if (testOneofCase_ == 9) {
          testOneofCase_ = 0;
          testOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string sub_message = 9;</code>
       * @param value The bytes for subMessage to set.
       * @return This builder for chaining.
       */
      public Builder setSubMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        testOneofCase_ = 9;
        testOneof_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SampleMessage)
    }

    // @@protoc_insertion_point(class_scope:SampleMessage)
    private static final protobuf.bean.SampleMessageOuterClass.SampleMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.bean.SampleMessageOuterClass.SampleMessage();
    }

    public static protobuf.bean.SampleMessageOuterClass.SampleMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SampleMessage>
        PARSER = new com.google.protobuf.AbstractParser<SampleMessage>() {
      @java.lang.Override
      public SampleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SampleMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SampleMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SampleMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.bean.SampleMessageOuterClass.SampleMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SampleMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SampleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SampleMessage.proto\"D\n\rSampleMessage\022\016" +
      "\n\004name\030\004 \001(\tH\000\022\025\n\013sub_message\030\t \001(\tH\000B\014\n" +
      "\ntest_oneofB\017\n\rprotobuf.beanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SampleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SampleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SampleMessage_descriptor,
        new java.lang.String[] { "Name", "SubMessage", "TestOneof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
