// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSearchResult2.proto

package protoBuf.bean;

public final class UserSearchResult2OuterClass {
  private UserSearchResult2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserSearchResult2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoBuf.bean.UserSearchResult2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    java.util.List<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry> 
        getDataList();
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry getData(int index);
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    java.util.List<? extends protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protoBuf.bean.UserSearchResult2}
   */
  public  static final class UserSearchResult2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoBuf.bean.UserSearchResult2)
      UserSearchResult2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserSearchResult2.newBuilder() to construct.
    private UserSearchResult2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserSearchResult2() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserSearchResult2();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserSearchResult2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.class, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.Builder.class);
    }

    public interface entryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protoBuf.bean.UserSearchResult2.entry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string key = 10;</code>
       * @return The key.
       */
      java.lang.String getKey();
      /**
       * <code>string key = 10;</code>
       * @return The bytes for key.
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>.User value = 20;</code>
       * @return Whether the value field is set.
       */
      boolean hasValue();
      /**
       * <code>.User value = 20;</code>
       * @return The value.
       */
      protobuf.bean.UserOuterClass.User getValue();
      /**
       * <code>.User value = 20;</code>
       */
      protobuf.bean.UserOuterClass.UserOrBuilder getValueOrBuilder();
    }
    /**
     * Protobuf type {@code protoBuf.bean.UserSearchResult2.entry}
     */
    public  static final class entry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protoBuf.bean.UserSearchResult2.entry)
        entryOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use entry.newBuilder() to construct.
      private entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private entry() {
        key_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new entry();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private entry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 82: {
                java.lang.String s = input.readStringRequireUtf8();

                key_ = s;
                break;
              }
              case 162: {
                protobuf.bean.UserOuterClass.User.Builder subBuilder = null;
                if (value_ != null) {
                  subBuilder = value_.toBuilder();
                }
                value_ = input.readMessage(protobuf.bean.UserOuterClass.User.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(value_);
                  value_ = subBuilder.buildPartial();
                }

                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_entry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.class, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder.class);
      }

      public static final int KEY_FIELD_NUMBER = 10;
      private volatile java.lang.Object key_;
      /**
       * <code>string key = 10;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        }
      }
      /**
       * <code>string key = 10;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUE_FIELD_NUMBER = 20;
      private protobuf.bean.UserOuterClass.User value_;
      /**
       * <code>.User value = 20;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return value_ != null;
      }
      /**
       * <code>.User value = 20;</code>
       * @return The value.
       */
      public protobuf.bean.UserOuterClass.User getValue() {
        return value_ == null ? protobuf.bean.UserOuterClass.User.getDefaultInstance() : value_;
      }
      /**
       * <code>.User value = 20;</code>
       */
      public protobuf.bean.UserOuterClass.UserOrBuilder getValueOrBuilder() {
        return getValue();
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getKeyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 10, key_);
        }
        if (value_ != null) {
          output.writeMessage(20, getValue());
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getKeyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, key_);
        }
        if (value_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(20, getValue());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry)) {
          return super.equals(obj);
        }
        protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry other = (protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry) obj;

        if (!getKey()
            .equals(other.getKey())) return false;
        if (hasValue() != other.hasValue()) return false;
        if (hasValue()) {
          if (!getValue()
              .equals(other.getValue())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
        if (hasValue()) {
          hash = (37 * hash) + VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getValue().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protoBuf.bean.UserSearchResult2.entry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protoBuf.bean.UserSearchResult2.entry)
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_entry_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_entry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.class, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder.class);
        }

        // Construct using protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          key_ = "";

          if (valueBuilder_ == null) {
            value_ = null;
          } else {
            value_ = null;
            valueBuilder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_entry_descriptor;
        }

        @java.lang.Override
        public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry getDefaultInstanceForType() {
          return protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.getDefaultInstance();
        }

        @java.lang.Override
        public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry build() {
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry buildPartial() {
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry result = new protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry(this);
          result.key_ = key_;
          if (valueBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = valueBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry) {
            return mergeFrom((protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry other) {
          if (other == protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.getDefaultInstance()) return this;
          if (!other.getKey().isEmpty()) {
            key_ = other.key_;
            onChanged();
          }
          if (other.hasValue()) {
            mergeValue(other.getValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object key_ = "";
        /**
         * <code>string key = 10;</code>
         * @return The key.
         */
        public java.lang.String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            key_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string key = 10;</code>
         * @return The bytes for key.
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string key = 10;</code>
         * @param value The key to set.
         * @return This builder for chaining.
         */
        public Builder setKey(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string key = 10;</code>
         * @return This builder for chaining.
         */
        public Builder clearKey() {
          
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>string key = 10;</code>
         * @param value The bytes for key to set.
         * @return This builder for chaining.
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          key_ = value;
          onChanged();
          return this;
        }

        private protobuf.bean.UserOuterClass.User value_;
        private com.google.protobuf.SingleFieldBuilderV3<
            protobuf.bean.UserOuterClass.User, protobuf.bean.UserOuterClass.User.Builder, protobuf.bean.UserOuterClass.UserOrBuilder> valueBuilder_;
        /**
         * <code>.User value = 20;</code>
         * @return Whether the value field is set.
         */
        public boolean hasValue() {
          return valueBuilder_ != null || value_ != null;
        }
        /**
         * <code>.User value = 20;</code>
         * @return The value.
         */
        public protobuf.bean.UserOuterClass.User getValue() {
          if (valueBuilder_ == null) {
            return value_ == null ? protobuf.bean.UserOuterClass.User.getDefaultInstance() : value_;
          } else {
            return valueBuilder_.getMessage();
          }
        }
        /**
         * <code>.User value = 20;</code>
         */
        public Builder setValue(protobuf.bean.UserOuterClass.User value) {
          if (valueBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            value_ = value;
            onChanged();
          } else {
            valueBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.User value = 20;</code>
         */
        public Builder setValue(
            protobuf.bean.UserOuterClass.User.Builder builderForValue) {
          if (valueBuilder_ == null) {
            value_ = builderForValue.build();
            onChanged();
          } else {
            valueBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.User value = 20;</code>
         */
        public Builder mergeValue(protobuf.bean.UserOuterClass.User value) {
          if (valueBuilder_ == null) {
            if (value_ != null) {
              value_ =
                protobuf.bean.UserOuterClass.User.newBuilder(value_).mergeFrom(value).buildPartial();
            } else {
              value_ = value;
            }
            onChanged();
          } else {
            valueBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.User value = 20;</code>
         */
        public Builder clearValue() {
          if (valueBuilder_ == null) {
            value_ = null;
            onChanged();
          } else {
            value_ = null;
            valueBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.User value = 20;</code>
         */
        public protobuf.bean.UserOuterClass.User.Builder getValueBuilder() {
          
          onChanged();
          return getValueFieldBuilder().getBuilder();
        }
        /**
         * <code>.User value = 20;</code>
         */
        public protobuf.bean.UserOuterClass.UserOrBuilder getValueOrBuilder() {
          if (valueBuilder_ != null) {
            return valueBuilder_.getMessageOrBuilder();
          } else {
            return value_ == null ?
                protobuf.bean.UserOuterClass.User.getDefaultInstance() : value_;
          }
        }
        /**
         * <code>.User value = 20;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            protobuf.bean.UserOuterClass.User, protobuf.bean.UserOuterClass.User.Builder, protobuf.bean.UserOuterClass.UserOrBuilder> 
            getValueFieldBuilder() {
          if (valueBuilder_ == null) {
            valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                protobuf.bean.UserOuterClass.User, protobuf.bean.UserOuterClass.User.Builder, protobuf.bean.UserOuterClass.UserOrBuilder>(
                    getValue(),
                    getParentForChildren(),
                    isClean());
            value_ = null;
          }
          return valueBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protoBuf.bean.UserSearchResult2.entry)
      }

      // @@protoc_insertion_point(class_scope:protoBuf.bean.UserSearchResult2.entry)
      private static final protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry();
      }

      public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<entry>
          PARSER = new com.google.protobuf.AbstractParser<entry>() {
        @java.lang.Override
        public entry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new entry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<entry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<entry> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    public int getSize() {
      return size_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry> data_;
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    public java.util.List<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    public java.util.List<? extends protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
     */
    public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2)) {
        return super.equals(obj);
      }
      protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 other = (protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoBuf.bean.UserSearchResult2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoBuf.bean.UserSearchResult2)
        protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.class, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.Builder.class);
      }

      // Construct using protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;

        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoBuf.bean.UserSearchResult2OuterClass.internal_static_protoBuf_bean_UserSearchResult2_descriptor;
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 getDefaultInstanceForType() {
        return protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.getDefaultInstance();
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 build() {
        protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 buildPartial() {
        protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 result = new protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2(this);
        int from_bitField0_ = bitField0_;
        result.size_ = size_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2) {
          return mergeFrom((protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 other) {
        if (other == protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>int32 size = 1;</code>
       * @return The size.
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder> dataBuilder_;

      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public java.util.List<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder setData(
          int index, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder setData(
          int index, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder addData(protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder addData(
          int index, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder addData(
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder addData(
          int index, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public java.util.List<? extends protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.getDefaultInstance());
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.getDefaultInstance());
      }
      /**
       * <code>repeated .protoBuf.bean.UserSearchResult2.entry data = 2;</code>
       */
      public java.util.List<protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entry.Builder, protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2.entryOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoBuf.bean.UserSearchResult2)
    }

    // @@protoc_insertion_point(class_scope:protoBuf.bean.UserSearchResult2)
    private static final protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2();
    }

    public static protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserSearchResult2>
        PARSER = new com.google.protobuf.AbstractParser<UserSearchResult2>() {
      @java.lang.Override
      public UserSearchResult2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserSearchResult2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserSearchResult2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserSearchResult2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoBuf.bean.UserSearchResult2OuterClass.UserSearchResult2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuf_bean_UserSearchResult2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuf_bean_UserSearchResult2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuf_bean_UserSearchResult2_entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuf_bean_UserSearchResult2_entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027UserSearchResult2.proto\022\rprotoBuf.bean" +
      "\032\nUser.proto\"\203\001\n\021UserSearchResult2\022\014\n\004si" +
      "ze\030\001 \001(\005\0224\n\004data\030\002 \003(\0132&.protoBuf.bean.U" +
      "serSearchResult2.entry\032*\n\005entry\022\013\n\003key\030\n" +
      " \001(\t\022\024\n\005value\030\024 \001(\0132\005.Userb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.bean.UserOuterClass.getDescriptor(),
        });
    internal_static_protoBuf_bean_UserSearchResult2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoBuf_bean_UserSearchResult2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuf_bean_UserSearchResult2_descriptor,
        new java.lang.String[] { "Size", "Data", });
    internal_static_protoBuf_bean_UserSearchResult2_entry_descriptor =
      internal_static_protoBuf_bean_UserSearchResult2_descriptor.getNestedTypes().get(0);
    internal_static_protoBuf_bean_UserSearchResult2_entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuf_bean_UserSearchResult2_entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    protobuf.bean.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
