// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSearchResult.proto

package protoBuf.bean;

public final class UserSearchResultOuterClass {
  private UserSearchResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserSearchResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoBuf.bean.UserSearchResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */
    boolean containsData(
        java.lang.String key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User>
    getData();
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */
    java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User>
    getDataMap();
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */

    protobuf.bean.UserOuterClass.User getDataOrDefault(
        java.lang.String key,
        protobuf.bean.UserOuterClass.User defaultValue);
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */

    protobuf.bean.UserOuterClass.User getDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code protoBuf.bean.UserSearchResult}
   */
  public  static final class UserSearchResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoBuf.bean.UserSearchResult)
      UserSearchResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserSearchResult.newBuilder() to construct.
    private UserSearchResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserSearchResult() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserSearchResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserSearchResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = com.google.protobuf.MapField.newMapField(
                    DataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, protobuf.bean.UserOuterClass.User>
              data__ = input.readMessage(
                  DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              data_.getMutableMap().put(
                  data__.getKey(), data__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoBuf.bean.UserSearchResultOuterClass.internal_static_protoBuf_bean_UserSearchResult_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoBuf.bean.UserSearchResultOuterClass.internal_static_protoBuf_bean_UserSearchResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.class, protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    public int getSize() {
      return size_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, protobuf.bean.UserOuterClass.User> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, protobuf.bean.UserOuterClass.User>newDefaultInstance(
                  protoBuf.bean.UserSearchResultOuterClass.internal_static_protoBuf_bean_UserSearchResult_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protobuf.bean.UserOuterClass.User.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, protobuf.bean.UserOuterClass.User> data_;
    private com.google.protobuf.MapField<java.lang.String, protobuf.bean.UserOuterClass.User>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */

    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */

    public java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */

    public protobuf.bean.UserOuterClass.User getDataOrDefault(
        java.lang.String key,
        protobuf.bean.UserOuterClass.User defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .User&gt; data = 2;</code>
     */

    public protobuf.bean.UserOuterClass.User getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      for (java.util.Map.Entry<java.lang.String, protobuf.bean.UserOuterClass.User> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, protobuf.bean.UserOuterClass.User>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, data__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoBuf.bean.UserSearchResultOuterClass.UserSearchResult)) {
        return super.equals(obj);
      }
      protoBuf.bean.UserSearchResultOuterClass.UserSearchResult other = (protoBuf.bean.UserSearchResultOuterClass.UserSearchResult) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!internalGetData().equals(
          other.internalGetData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoBuf.bean.UserSearchResultOuterClass.UserSearchResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoBuf.bean.UserSearchResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoBuf.bean.UserSearchResult)
        protoBuf.bean.UserSearchResultOuterClass.UserSearchResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoBuf.bean.UserSearchResultOuterClass.internal_static_protoBuf_bean_UserSearchResult_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoBuf.bean.UserSearchResultOuterClass.internal_static_protoBuf_bean_UserSearchResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.class, protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.Builder.class);
      }

      // Construct using protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;

        internalGetMutableData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoBuf.bean.UserSearchResultOuterClass.internal_static_protoBuf_bean_UserSearchResult_descriptor;
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResultOuterClass.UserSearchResult getDefaultInstanceForType() {
        return protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.getDefaultInstance();
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResultOuterClass.UserSearchResult build() {
        protoBuf.bean.UserSearchResultOuterClass.UserSearchResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protoBuf.bean.UserSearchResultOuterClass.UserSearchResult buildPartial() {
        protoBuf.bean.UserSearchResultOuterClass.UserSearchResult result = new protoBuf.bean.UserSearchResultOuterClass.UserSearchResult(this);
        int from_bitField0_ = bitField0_;
        result.size_ = size_;
        result.data_ = internalGetData();
        result.data_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoBuf.bean.UserSearchResultOuterClass.UserSearchResult) {
          return mergeFrom((protoBuf.bean.UserSearchResultOuterClass.UserSearchResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoBuf.bean.UserSearchResultOuterClass.UserSearchResult other) {
        if (other == protoBuf.bean.UserSearchResultOuterClass.UserSearchResult.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoBuf.bean.UserSearchResultOuterClass.UserSearchResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoBuf.bean.UserSearchResultOuterClass.UserSearchResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>int32 size = 1;</code>
       * @return The size.
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, protobuf.bean.UserOuterClass.User> data_;
      private com.google.protobuf.MapField<java.lang.String, protobuf.bean.UserOuterClass.User>
      internalGetData() {
        if (data_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        return data_;
      }
      private com.google.protobuf.MapField<java.lang.String, protobuf.bean.UserOuterClass.User>
      internalGetMutableData() {
        onChanged();;
        if (data_ == null) {
          data_ = com.google.protobuf.MapField.newMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        if (!data_.isMutable()) {
          data_ = data_.copy();
        }
        return data_;
      }

      public int getDataCount() {
        return internalGetData().getMap().size();
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */

      public boolean containsData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */

      public java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> getDataMap() {
        return internalGetData().getMap();
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */

      public protobuf.bean.UserOuterClass.User getDataOrDefault(
          java.lang.String key,
          protobuf.bean.UserOuterClass.User defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> map =
            internalGetData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */

      public protobuf.bean.UserOuterClass.User getDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> map =
            internalGetData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearData() {
        internalGetMutableData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */

      public Builder removeData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User>
      getMutableData() {
        return internalGetMutableData().getMutableMap();
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */
      public Builder putData(
          java.lang.String key,
          protobuf.bean.UserOuterClass.User value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .User&gt; data = 2;</code>
       */

      public Builder putAllData(
          java.util.Map<java.lang.String, protobuf.bean.UserOuterClass.User> values) {
        internalGetMutableData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoBuf.bean.UserSearchResult)
    }

    // @@protoc_insertion_point(class_scope:protoBuf.bean.UserSearchResult)
    private static final protoBuf.bean.UserSearchResultOuterClass.UserSearchResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoBuf.bean.UserSearchResultOuterClass.UserSearchResult();
    }

    public static protoBuf.bean.UserSearchResultOuterClass.UserSearchResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserSearchResult>
        PARSER = new com.google.protobuf.AbstractParser<UserSearchResult>() {
      @java.lang.Override
      public UserSearchResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserSearchResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserSearchResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserSearchResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protoBuf.bean.UserSearchResultOuterClass.UserSearchResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuf_bean_UserSearchResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuf_bean_UserSearchResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoBuf_bean_UserSearchResult_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoBuf_bean_UserSearchResult_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026UserSearchResult.proto\022\rprotoBuf.bean\032" +
      "\nUser.proto\"\215\001\n\020UserSearchResult\022\014\n\004size" +
      "\030\001 \001(\005\0227\n\004data\030\002 \003(\0132).protoBuf.bean.Use" +
      "rSearchResult.DataEntry\0322\n\tDataEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\024\n\005value\030\002 \001(\0132\005.User:\0028\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.bean.UserOuterClass.getDescriptor(),
        });
    internal_static_protoBuf_bean_UserSearchResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoBuf_bean_UserSearchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuf_bean_UserSearchResult_descriptor,
        new java.lang.String[] { "Size", "Data", });
    internal_static_protoBuf_bean_UserSearchResult_DataEntry_descriptor =
      internal_static_protoBuf_bean_UserSearchResult_descriptor.getNestedTypes().get(0);
    internal_static_protoBuf_bean_UserSearchResult_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoBuf_bean_UserSearchResult_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    protobuf.bean.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
